# Generated by Django 2.0.7 on 2019-05-05 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190505_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('repayment_img', models.ImageField(blank=True, null=True, upload_to='repayment_img/')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_ids', to='dashboard.Loan')),
            ],
        ),
    ]
