# Generated by Django 2.0.7 on 2019-05-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='amount',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
