# Generated by Django 2.0.7 on 2019-05-06 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20190506_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
