# Generated by Django 2.0.7 on 2019-05-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_repayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
