# Generated by Django 2.0.7 on 2019-05-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_auto_20190506_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='admin_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayment_admin_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
