# Generated by Django 2.0.7 on 2019-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190217_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.IntegerField(blank=True, default='0000000000', null=True, verbose_name='bvn'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(blank=True, default='0909090909090', null=True, verbose_name='phone no'),
        ),
    ]
