# Generated by Django 2.0.7 on 2019-05-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190503_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, default='0909090909090', max_length=14, null=True, verbose_name='phone no'),
        ),
    ]
