# Generated by Django 2.0.7 on 2019-05-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190503_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='active token'),
        ),
    ]
