# Generated by Django 2.0.7 on 2019-05-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_active_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_token',
            new_name='confirmation_token',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
