# Generated by Django 2.0.7 on 2019-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190504_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_token',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='activation token'),
        ),
    ]
